version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
      - ./logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - backend
      - frontend

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "6001:80"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
